nelmio_cors:
  defaults:
    allow_origin: ["%env(resolve:CORS_ALLOW_ORIGIN)%"]
    allow_credentials: true
    allow_headers: ["Content-Type", "Authorization"]
    allow_methods: ["GET", "POST", "OPTIONS", "PATCH", "PUT", "DELETE"]
    expose_headers: ["Link"]
    max_age: 3600
  paths:
    "^/api/": ~
