# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"

    App\EventListener\JWTSuccessHandler:
        tags:
            - {
                  name: kernel.event_listener,
                  event: lexik_jwt_authentication.on_authentication_success,
                  method: onAuthenticationSuccess,
                  priority: 10,
              }

    App\EventListener\JWTAuthenticationListener:
        tags:
            - {
                  name: kernel.event_listener,
                  event: lexik_jwt_authentication.on_jwt_authenticated,
                  method: onJWTAuthenticated,
              }

    App\EventListener\JWTResponseCleaner:
        tags:
            - {
                  name: kernel.event_listener,
                  event: lexik_jwt_authentication.on_authentication_success,
                  method: onAuthenticationSuccess,
                  priority: 100,
              }

    App\EventListener\JWTAuthenticationFailureHandler:
        tags:
            - {
                  name: kernel.event_listener,
                  event: lexik_jwt_authentication.on_authentication_failure,
                  method: onAuthenticationFailure,
              }

    App\Service\MailerSendEmailService:
        arguments:
            $defaultFrom: '%env(MAILERSEND_FROM)%'
            $apiKey: '%env(MAILERSEND_API_KEY)%'

    App\Service\EmailServiceInterface: '@App\Service\MailerSendEmailService'

    App\Service\EmailVerificationService:
        arguments:
            $appUrl: '%env(APP_URL)%'

    App\Service\PasswordResetService:
        arguments:
            $appUrl: '%env(APP_URL)%'

    App\Service\GoogleAuthService:
        arguments:
            $googleClientId: '%env(GOOGLE_CLIENT_ID)%'

    App\Service\RiotApiService:
        arguments:
            $riotApiKey: '%env(RIOT_API_KEY)%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
